### ISSUE TITLE
No package.json & bower.json file present

### ISSUE THREAD

**Issue by jagdishmastek** [mohsiur/generator-aws-lambda-maven#1]
I had tried to create project but every time I am getting below error.Please help. 

I'm all done. Running npm install && bower install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN saveError ENOENT: no such file or directory, open 'D:\maven\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\maven\package.json'
npm WARN maven No description
npm WARN maven No repository field.
npm WARN maven No README data
npm WARN maven No license field.

up to date in 0.083s
bower                           ENOENT No bower.json present

**Comment by mohsiur** [comment]
So I believe I published a broken version on to NPM, as I'm refactoring the code, I have updated it you can try again now, and it should work. Please keep an eye on this branch, the new version should be up and running soon.

**Comment by mohsiur** [comment]
@jagdishmastek please check the latest release, it should be all working now
